ALTER TABLE `desarrollo_cloud`.`nombre_tabla`
  ADD COLUMN `userAdd` VARCHAR(25) NULL DEFAULT NULL,
  ADD COLUMN `fhAdd` DATETIME NULL DEFAULT NULL,
  ADD COLUMN `userEdit` VARCHAR(25) NULL DEFAULT NULL,
  ADD COLUMN `fhEdit` DATETIME NULL DEFAULT NULL,
  ADD COLUMN `flgDelete` INT(1) DEFAULT 0,
  ADD COLUMN `userDelete` VARCHAR(25) NULL DEFAULT NULL,
  ADD COLUMN `fhDelete` DATETIME NULL DEFAULT NULL,
  ADD COLUMN `obsCrud` LONGTEXT NULL DEFAULT NULL;